package com.itj.bootcamp.taskflow;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.UUID;

/**
 * Now a JPA entity. The id is generated by the database, not by us.
 * (This is the persistence shape — clients still see TaskResponse, not this.)
 */
@Entity
@Table(name = "tasks")
public class Task {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID taskId;

    @Column(nullable = false)
    private String title;

    private String description;

    private Instant completed;

    @CreationTimestamp
    @Column(updatable = false)
    private Instant entryDate;

    /** JPA requires a no-arg constructor. */
    protected Task() {
    }

    public Task(String title) {
        this.title = title;
    }

    public UUID getTaskId() {
        return taskId;
    }

    public Instant getEntryDate() {
        return entryDate;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isCompleted() {
        return completed  != null;
    }

    public void setCompleted(Instant completed) {
        this.completed = completed;
    }

    @Override
    public String toString() {
        return "Task{id=" + taskId + ", title='" + title + "', completed=" + completed + "}";
    }
}
